version: "3.9"
services:
  go-gemini-telegram-bot:
    image: ghcr.io/ihkeep/go-gemini-telegram-bot:latest
    container_name: go-gemini-telegram-bot
    restart: always
    environment:
      TZ: Asia/Shanghai
      BOT_TOKEN: 
      Gemini_API_KEY: 



  # -------------------------------------------------
  # go-gemini-telegram-bot:
  #   image: ghcr.io/ihkeep/go-gemini-telegram-bot:latest
  #   container_name: go-gemini-telegram-bot
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   environment:
  #     TZ: Asia/Shanghai
  #     BOT_TOKEN: 
  #     Gemini_API_KEY: 